# Generated by Django 4.2.6 on 2023-11-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoriaNome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteNome', models.CharField(verbose_name=500)),
                ('ClienteIdade', models.PositiveSmallIntegerField()),
                ('ClienteCpf', models.CharField(verbose_name=14)),
                ('ClienteGenero', models.CharField(verbose_name=9)),
                ('ClienteEmail', models.CharField(verbose_name=40)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ProdutoID', models.AutoField(primary_key=True, serialize=False)),
                ('ProdutoCodigo', models.UUIDField()),
                ('ProdutoNome', models.CharField(max_length=60)),
                ('ProdutoDescricao', models.CharField(max_length=500)),
                ('ProdutoPreco', models.FloatField()),
                ('ProdutoTamanho', models.CharField(verbose_name=10)),
                ('Produtocategoria', models.ManyToManyField(related_name='produtos', to='EcoMmerce.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('PedidoID', models.AutoField(primary_key=True, serialize=False)),
                ('PedidoMetodoPagamento', models.CharField(verbose_name=15)),
                ('PedidoStatus', models.CharField(verbose_name=60)),
                ('PedidoData', models.DateField()),
                ('PedidoEndereco', models.CharField(verbose_name=500)),
                ('PedidoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='EcoMmerce.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('ItemPedidoID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemPedidoQuantidade', models.PositiveSmallIntegerField()),
                ('ItemPedidoPrecoUnitario', models.FloatField()),
                ('ItemPedidoPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedidos', to='EcoMmerce.pedido')),
                ('ItemPedidoPorProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedidos', to='EcoMmerce.produto')),
            ],
        ),
    ]
